export default {
  // _globalReducer
  STATUS_PAGE_SET: 'STATUS_PAGE_REDUCER_SET',
  STATUS_PAGE_SET_MULTIPLE: 'STATUS_PAGE_REDUCER_SET_MULTIPLE',
  STATUS_PAGE_RESET: 'STATUS_PAGE_REDUCER_RESET',
  STATUS_PAGE_RESET_ALL: 'STATUS_PAGE_REDUCER_RESET_ALL',

  SET_BARANG: 'SET_BARANG',
  ADD_BARANG: 'ADD_BARANG',

  SET_MODAL_UP: 'SET_MODAL_UP',
  SET_MODAL_CLOSED: 'SET_MODAL_CLOSED',

  ADD_CART: 'ADD_CART',
};
