export const barang = [
  {
    name: 'samsung smartgreen led',
    harga: 2000000,
    ukuran: '24 inch',
    android: 'iya',
    kode: '#1a',
  },
  {
    name: 'samsung smartgreen lcd',
    harga: 1700000,
    ukuran: '24 inch',
    android: 'iya',
    kode: '#1b',
  },
  {
    name: 'samsung smartgreen led',
    harga: 3800000,
    ukuran: '27 inch',
    android: 'iya',
    kode: '#2a',
  },
  {
    name: 'samsung smartgreen lcd',
    harga: 3200000,
    ukuran: '27 inch',
    android: 'iya',
    kode: '#2b',
  },
  {
    name: 'samsung smartgreen led',
    harga: 5000000,
    ukuran: '32 inch',
    android: 'iya',
    kode: '#3a',
  },
  {
    name: 'samsung smartgreen lcd',
    harga: 4800000,
    ukuran: '32 inch',
    android: 'iya',
    kode: '#3b',
  },
  {
    name: 'ultrawide samsung smartgreen led',
    harga: 5800000,
    ukuran: '42 inch',
    android: 'iya',
    kode: '#4a',
  },
  {
    name: 'ultrawide samsung smartgreen lcd',
    harga: 5200000,
    ukuran: '42 inch',
    android: 'iya',
    kode: '#4b',
  },
];